"""Update egrul_egrip table Organization

Revision ID: 566c7b0d26bf
Revises: 5e1d6c55115e
Create Date: 2025-05-26 22:24:19.916347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566c7b0d26bf'
down_revision = '5e1d6c55115e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('egrul_egrip',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('egrul_egrip',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###
