"""Initial migration

Revision ID: 7ce37c9a9264
Revises: 
Create Date: 2025-06-04 22:42:52.490270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce37c9a9264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('okved', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=1024), nullable=False),
    sa.Column('first_name', sa.String(length=1024), nullable=False),
    sa.Column('patronymic', sa.String(length=1024), nullable=True),
    sa.Column('login', sa.String(length=129), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('regulatory_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.String(length=4096), nullable=False),
    sa.Column('measure', sa.String(length=10), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=1024), nullable=False),
    sa.Column('first_name', sa.String(length=1024), nullable=False),
    sa.Column('patronymic', sa.String(length=1024), nullable=True),
    sa.Column('login', sa.String(length=129), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('jur_address', sa.String(length=1024), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('egrul_egrip', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organization'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_entity', sa.Integer(), nullable=True),
    sa.Column('name_attribute', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['id_entity'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_entity', sa.Integer(), nullable=True),
    sa.Column('link_picture', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['id_entity'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_entity', sa.Integer(), nullable=True),
    sa.Column('status_request', sa.String(length=16), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.Column('okved', sa.String(length=6), nullable=True),
    sa.Column('id_bank', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id_bank'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['id_entity'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_request', sa.Integer(), nullable=True),
    sa.Column('status_request', sa.String(length=9), nullable=True),
    sa.Column('link_inference', sa.String(length=4096), nullable=False),
    sa.Column('id_security_requirements', sa.Integer(), nullable=True),
    sa.Column('id_regulatory_document', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_regulatory_document'], ['regulatory_document.id'], ),
    sa.ForeignKeyConstraint(['id_request'], ['request.id'], ),
    sa.ForeignKeyConstraint(['id_security_requirements'], ['security_requirements.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expertise')
    op.drop_table('request')
    op.drop_table('picture_entity')
    op.drop_table('attribute_entity')
    op.drop_table('entity')
    op.drop_table('organization')
    op.drop_table('worker')
    op.drop_table('security_requirements')
    op.drop_table('regulatory_document')
    op.drop_table('customer')
    op.drop_table('bank')
    # ### end Alembic commands ###
