"""Initial migration

Revision ID: 9b9fa1045da3
Revises: 
Create Date: 2025-06-14 14:29:21.414331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9fa1045da3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expertise', schema=None) as batch_op:
        batch_op.alter_column('link_inference',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expertise', schema=None) as batch_op:
        batch_op.alter_column('link_inference',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)

    # ### end Alembic commands ###
