"""Initial migration

Revision ID: 9fb122c2114e
Revises: 7ce37c9a9264
Create Date: 2025-06-05 00:16:24.025009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb122c2114e'
down_revision = '7ce37c9a9264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('link_material',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('link_material',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)

    # ### end Alembic commands ###
