"""Initial migration

Revision ID: b6e082d2bed2
Revises: 
Create Date: 2025-05-22 01:30:50.648325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e082d2bed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('okved', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.String(length=4096), nullable=False),
    sa.Column('measure', sa.String(length=10), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=1024), nullable=False),
    sa.Column('first_name', sa.String(length=1024), nullable=False),
    sa.Column('patronymic', sa.String(length=1024), nullable=True),
    sa.Column('login', sa.String(length=129), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_organization'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('link_picture', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('id_worker', sa.Integer(), nullable=True),
    sa.Column('id_object', sa.Integer(), nullable=True),
    sa.Column('status_request', sa.String(length=1), nullable=True),
    sa.Column('link_material', sa.String(length=4096), nullable=False),
    sa.Column('okved', sa.String(length=6), nullable=True),
    sa.Column('id_bank', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id_bank'], ['bank.id'], ),
    sa.ForeignKeyConstraint(['id_object'], ['object.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('kpp',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('egrul_egrip',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('egrul_egrip',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('kpp',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    op.drop_table('request')
    op.drop_table('picture_object')
    op.drop_table('attribute_object')
    op.drop_table('object')
    op.drop_table('worker')
    op.drop_table('security_requirements')
    op.drop_table('regulatory_document')
    op.drop_table('bank')
    # ### end Alembic commands ###
